// lib/food_data.dart
final Map<String, List<Map<String, dynamic>>> foodMaster = {
  "肉類": [
    {"name": "鶏むね肉", "icon": "🍗", "limit": 2},
    {"name": "鶏もも肉", "icon": "🍗", "limit": 2},
    {"name": "鶏手羽先", "icon": "🍗", "limit": 2},
    {"name": "豚バラ肉", "icon": "🥩", "limit": 3},
    {"name": "豚ロース肉", "icon": "🥩", "limit": 3},
    {"name": "豚こま肉", "icon": "🥩", "limit": 3},
    {"name": "牛ステーキ肉", "icon": "🥩", "limit": 3},
    {"name": "牛細切れ肉", "icon": "🥩", "limit": 3},
    {"name": "ひき肉", "icon": "🥡", "limit": 1},
    {"name": "ハム", "icon": "🥓", "limit": 7},
    {"name": "ソーセージ", "icon": "🥓", "limit": 7},
    {"name": "ベーコン", "icon": "🥓", "limit": 7},
    {"name": "厚切りベーコン", "icon": "🥓", "limit": 7},
  ],
  "魚介類": [
    {"name": "鮭の切り身", "icon": "🐟", "limit": 3},
    {"name": "刺身", "icon": "🍣", "limit": 1},
    {"name": "えび", "icon": "🦐", "limit": 2},
    {"name": "いか", "icon": "🦑", "limit": 2},
    {"name": "あじ", "icon": "🐟", "limit": 2},
    {"name": "いわし", "icon": "🐟", "limit": 2},
    {"name": "さば", "icon": "🐟", "limit": 2},
    {"name": "さんま", "icon": "🐟", "limit": 2},
    {"name": "たこ", "icon": "🐙", "limit": 2},
    {"name": "あさり", "icon": "🐚", "limit": 2},
    {"name": "しじみ", "icon": "🐚", "limit": 2},
    {"name": "ほたて", "icon": "🐚", "limit": 2},
    {"name": "カニカマ", "icon": "🦀", "limit": 7},
  ],
  "野菜": [
    {"name": "キャベツ", "icon": "🥬", "limit": 7},
    {"name": "たまねぎ", "icon": "🧅", "limit": 21},
    {"name": "にんじん", "icon": "🥕", "limit": 14},
    {"name": "もやし", "icon": "🌱", "limit": 2},
    {"name": "ブロッコリー", "icon": "🥦", "limit": 4},
    {"name": "レタス", "icon": "🥗", "limit": 3},
    {"name": "白菜", "icon": "🥬", "limit": 7},
    {"name": "小松菜", "icon": "🥬", "limit": 3},
    {"name": "ほうれん草", "icon": "🥬", "limit": 3},
    {"name": "ピーマン", "icon": "🫑", "limit": 7},
    {"name": "ナス", "icon": "🍆", "limit": 5},
    {"name": "トマト", "icon": "🍅", "limit": 5},
    {"name": "ミニトマト", "icon": "🍅", "limit": 7},
    {"name": "きゅうり", "icon": "🥒", "limit": 5},
    {"name": "大根", "icon": "🥢", "limit": 10},
    {"name": "じゃがいも", "icon": "🥔", "limit": 30},
    {"name": "さつまいも", "icon": "🍠", "limit": 30},
    {"name": "かぼちゃ", "icon": "🎃", "limit": 14},
    {"name": "長ねぎ", "icon": "🌱", "limit": 10},
  ],
  "果物": [
    {"name": "りんご", "icon": "🍎", "limit": 14},
    {"name": "バナナ", "icon": "🍌", "limit": 5},
    {"name": "いちご", "icon": "🍓", "limit": 2},
    {"name": "みかん", "icon": "🍊", "limit": 14},
    {"name": "グレープフルーツ", "icon": "🍊", "limit": 10},
    {"name": "ぶどう", "icon": "🍇", "limit": 5},
    {"name": "キウイ", "icon": "🥝", "limit": 10},
    {"name": "パイナップル", "icon": "🍍", "limit": 5},
  ],
  "乳製品・卵": [
    {"name": "卵", "icon": "🥚", "limit": 14},
    {"name": "牛乳", "icon": "🥛", "limit": 5},
    {"name": "ヨーグルト", "icon": "🍦", "limit": 7},
    {"name": "バター", "icon": "🧈", "limit": 60},
    {"name": "チーズ", "icon": "🧀", "limit": 20},
    {"name": "生クリーム", "icon": "🍰", "limit": 3},
  ],
  "飲み物": [
    {"name": "お茶", "icon": "🍵", "limit": 4},
    {"name": "麦茶", "icon": "🍵", "limit": 3},
    {"name": "ジュース", "icon": "🧃", "limit": 4},
    {"name": "コーラ", "icon": "🥤", "limit": 7},
    {"name": "炭酸水", "icon": "🥤", "limit": 7},
    {"name": "コーヒー", "icon": "☕", "limit": 3},
    {"name": "ビール", "icon": "🍺", "limit": 30},
    {"name": "発泡酒", "icon": "🍺", "limit": 30},
    {"name": "ワイン", "icon": "🍷", "limit": 30},
    {"name": "日本酒", "icon": "🍶", "limit": 60},
  ],
  "調味料": [
    {"name": "マヨネーズ", "icon": "🧴", "limit": 30},
    {"name": "ケチャップ", "icon": "🍅", "limit": 30},
    {"name": "味噌", "icon": "🍲", "limit": 90},
    {"name": "醤油", "icon": "🍶", "limit": 60},
    {"name": "料理酒", "icon": "🍶", "limit": 60},
    {"name": "みりん", "icon": "🍯", "limit": 60},
    {"name": "酢", "icon": "🍾", "limit": 90},
    {"name": "めんつゆ", "icon": "🍲", "limit": 30},
    {"name": "焼肉のタレ", "icon": "🍖", "limit": 30},
    {"name": "ポン酢", "icon": "🍋", "limit": 30},
  ],
  "キノコ類": [
    {"name": "しいたけ", "icon": "🍄", "limit": 5},
    {"name": "しめじ", "icon": "🍄", "limit": 5},
    {"name": "えのき", "icon": "🍄", "limit": 3},
    {"name": "エリンギ", "icon": "🍄", "limit": 5},
    {"name": "まいたけ", "icon": "🍄", "limit": 5},
    {"name": "なめこ", "icon": "🍄", "limit": 2},
  ],
  "お菓子": [
    {"name": "チョコ", "icon": "🍫", "limit": 30},
    {"name": "アイス", "icon": "🍦", "limit": 60},
    {"name": "ケーキ", "icon": "🍰", "limit": 1},
    {"name": "プリン", "icon": "🍮", "limit": 3},
    {"name": "ゼリー", "icon": "🍮", "limit": 7},
    {"name": "ポテトチップス", "icon": "🥔", "limit": 20},
    {"name": "クッキー", "icon": "🍪", "limit": 30},
  ],
  "その他": [
    {"name": "納豆", "icon": "🥢", "limit": 7},
    {"name": "豆腐", "icon": "⬜", "limit": 3},
    {"name": "油揚げ", "icon": "🦊", "limit": 4},
    {"name": "ちくわ", "icon": "🌀", "limit": 5},
    {"name": "こんにゃく", "icon": "⬛", "limit": 14},
  ],
  "お米": [
      {"name": "こしひかり", "icon": "米", "limit": 7},
  ]
};