// 食材マスターデータ
// limit = 目安の保存日数（実際の消費期限・保存方法は商品の表示を確認してください）
final Map<String, List<Map<String, dynamic>>> foodMaster = {

  // ── 鶏肉 ──────────────────────────────────────────────
  "鶏肉": [
    {"name": "鶏むね肉",           "icon": "🍗", "limit": 2},
    {"name": "鶏もも肉",           "icon": "🍗", "limit": 2},
    {"name": "鶏ささみ",           "icon": "🍗", "limit": 2},
    {"name": "鶏こま切れ肉",       "icon": "🍗", "limit": 2},
    {"name": "鶏ひき肉",           "icon": "🥡", "limit": 1},
    {"name": "手羽先",             "icon": "🍗", "limit": 2},
    {"name": "手羽元",             "icon": "🍗", "limit": 2},
    {"name": "手羽中",             "icon": "🍗", "limit": 2},
    {"name": "手羽肉",             "icon": "🍗", "limit": 2},
    {"name": "鶏皮",               "icon": "🍗", "limit": 2},
    {"name": "鶏せせり",           "icon": "🍗", "limit": 2},
    {"name": "鶏レバー",           "icon": "🍗", "limit": 2},
    {"name": "鶏ハツ",             "icon": "🍗", "limit": 2},
    {"name": "砂肝",               "icon": "🍗", "limit": 2},
    {"name": "やげん軟骨",         "icon": "🍗", "limit": 2},
    {"name": "鶏なんこつ",         "icon": "🍗", "limit": 2},
    {"name": "鶏唐揚げ用",         "icon": "🍗", "limit": 2},
    {"name": "鶏鍋用",             "icon": "🍗", "limit": 2},
    {"name": "鶏焼肉用",           "icon": "🍗", "limit": 2},
    {"name": "鶏照り焼き用",       "icon": "🍗", "limit": 2},
  ],

  // ── 豚肉 ──────────────────────────────────────────────
  "豚肉": [
    {"name": "豚バラ肉（厚切り）", "icon": "🥩", "limit": 3},
    {"name": "豚バラ肉（薄切り）", "icon": "🥩", "limit": 3},
    {"name": "豚ロース（厚切り）", "icon": "🥩", "limit": 3},
    {"name": "豚ロース（薄切り）", "icon": "🥩", "limit": 3},
    {"name": "豚肩ロース（厚切り）","icon": "🥩", "limit": 3},
    {"name": "豚肩ロース（薄切り）","icon": "🥩", "limit": 3},
    {"name": "豚もも肉（厚切り）", "icon": "🥩", "limit": 3},
    {"name": "豚もも肉（薄切り）", "icon": "🥩", "limit": 3},
    {"name": "豚こま切れ肉",       "icon": "🥩", "limit": 3},
    {"name": "豚ひき肉",           "icon": "🥡", "limit": 1},
    {"name": "豚しゃぶしゃぶ肉",   "icon": "🥩", "limit": 3},
    {"name": "豚ヒレ肉",           "icon": "🥩", "limit": 3},
    {"name": "豚スペアリブ",       "icon": "🥩", "limit": 3},
    {"name": "豚角切り肉",         "icon": "🥩", "limit": 3},
    {"name": "豚レバー",           "icon": "🥩", "limit": 2},
    {"name": "豚タン",             "icon": "🥩", "limit": 2},
    {"name": "豚ハツ",             "icon": "🥩", "limit": 2},
    {"name": "豚軟骨",             "icon": "🥩", "limit": 2},
    {"name": "豚耳",               "icon": "🥩", "limit": 2},
    {"name": "豚カツ用",           "icon": "🥩", "limit": 3},
    {"name": "豚生姜焼き用",       "icon": "🥩", "limit": 3},
    {"name": "豚ソテー用",         "icon": "🥩", "limit": 3},
    {"name": "豚焼肉用",           "icon": "🥩", "limit": 3},
    {"name": "豚丼用",             "icon": "🥩", "limit": 3},
    {"name": "豚汁用",             "icon": "🥩", "limit": 3},
  ],

  // ── 牛肉 ──────────────────────────────────────────────
  "牛肉": [
    {"name": "牛バラ肉（厚切り）", "icon": "🥩", "limit": 3},
    {"name": "牛バラ肉（薄切り）", "icon": "🥩", "limit": 3},
    {"name": "牛肩肉",             "icon": "🥩", "limit": 3},
    {"name": "牛肩ロース（厚切り）","icon": "🥩", "limit": 3},
    {"name": "牛肩ロース（薄切り）","icon": "🥩", "limit": 3},
    {"name": "牛リブロース",       "icon": "🥩", "limit": 3},
    {"name": "牛サーロイン",       "icon": "🥩", "limit": 3},
    {"name": "牛ヒレ肉",           "icon": "🥩", "limit": 3},
    {"name": "牛もも肉（厚切り）", "icon": "🥩", "limit": 3},
    {"name": "牛もも肉（薄切り）", "icon": "🥩", "limit": 3},
    {"name": "牛こま切れ肉",       "icon": "🥩", "limit": 3},
    {"name": "牛切り落とし肉",     "icon": "🥩", "limit": 3},
    {"name": "牛ひき肉",           "icon": "🥡", "limit": 1},
    {"name": "牛ハラミ",           "icon": "🥩", "limit": 3},
    {"name": "牛タン",             "icon": "🥩", "limit": 3},
    {"name": "牛レバー",           "icon": "🥩", "limit": 2},
    {"name": "牛ハツ",             "icon": "🥩", "limit": 2},
    {"name": "牛ミノ",             "icon": "🥩", "limit": 2},
    {"name": "牛センマイ",         "icon": "🥩", "limit": 2},
    {"name": "牛テール",           "icon": "🥩", "limit": 3},
    {"name": "牛すじ肉",           "icon": "🥩", "limit": 3},
    {"name": "牛ステーキ用",       "icon": "🥩", "limit": 3},
    {"name": "牛焼肉用",           "icon": "🥩", "limit": 3},
    {"name": "牛しゃぶしゃぶ用",   "icon": "🥩", "limit": 3},
    {"name": "牛すき焼き用",       "icon": "🥩", "limit": 3},
    {"name": "牛丼用",             "icon": "🥩", "limit": 3},
  ],

  // ── その他の肉 ────────────────────────────────────────
  "その他の肉": [
    {"name": "合挽き肉",           "icon": "🥡", "limit": 1},
    {"name": "ラム肉（ロース）",   "icon": "🥩", "limit": 3},
    {"name": "ラム肉（もも）",     "icon": "🥩", "limit": 3},
    {"name": "ラム肉（肩）",       "icon": "🥩", "limit": 3},
    {"name": "ラムラック",         "icon": "🥩", "limit": 3},
    {"name": "ラムチョップ",       "icon": "🥩", "limit": 3},
    {"name": "ラムしゃぶしゃぶ用", "icon": "🥩", "limit": 3},
    {"name": "ラム焼肉用",         "icon": "🥩", "limit": 3},
    {"name": "鴨肉",               "icon": "🍗", "limit": 2},
    {"name": "鴨ロース",           "icon": "🍗", "limit": 2},
    {"name": "馬肉",               "icon": "🥩", "limit": 2},
    {"name": "馬刺し",             "icon": "🥩", "limit": 2},
    {"name": "猪肉",               "icon": "🥩", "limit": 2},
    {"name": "鹿肉",               "icon": "🥩", "limit": 2},
    {"name": "山羊肉",             "icon": "🥩", "limit": 2},
  ],

  // ── 加工肉・ハム・ソーセージ ─────────────────────────
  "加工肉・ハム類": [
    {"name": "ロースハム",             "icon": "🥓", "limit": 7},
    {"name": "ボンレスハム",           "icon": "🥓", "limit": 7},
    {"name": "ショルダーハム",         "icon": "🥓", "limit": 7},
    {"name": "プレスハム",             "icon": "🥓", "limit": 7},
    {"name": "生ハム",                 "icon": "🥓", "limit": 7},
    {"name": "プロシュート",           "icon": "🥓", "limit": 7},
    {"name": "ベーコン",               "icon": "🥓", "limit": 7},
    {"name": "厚切りベーコン",         "icon": "🥓", "limit": 7},
    {"name": "ショルダーベーコン",     "icon": "🥓", "limit": 7},
    {"name": "ロースベーコン",         "icon": "🥓", "limit": 7},
    {"name": "パンチェッタ",           "icon": "🥓", "limit": 7},
    {"name": "ウインナー",             "icon": "🌭", "limit": 7},
    {"name": "フランクフルト",         "icon": "🌭", "limit": 7},
    {"name": "ボロニアソーセージ",     "icon": "🌭", "limit": 7},
    {"name": "チョリソー",             "icon": "🌭", "limit": 7},
    {"name": "サラミ",                 "icon": "🥓", "limit": 14},
    {"name": "ペパロニ",               "icon": "🥓", "limit": 14},
    {"name": "生ソーセージ",           "icon": "🌭", "limit": 3},
    {"name": "ハーブソーセージ",       "icon": "🌭", "limit": 7},
    {"name": "粗挽きソーセージ",       "icon": "🌭", "limit": 7},
    {"name": "焼き豚（チャーシュー）", "icon": "🥓", "limit": 5},
    {"name": "煮豚",                   "icon": "🥓", "limit": 5},
    {"name": "ローストビーフ",         "icon": "🥩", "limit": 5},
    {"name": "鶏ハム",                 "icon": "🍗", "limit": 5},
    {"name": "サラダチキン",           "icon": "🍗", "limit": 5},
    {"name": "スモークチキン",         "icon": "🍗", "limit": 5},
    {"name": "蒸し鶏",                 "icon": "🍗", "limit": 3},
    {"name": "ミートボール",           "icon": "🍖", "limit": 5},
    {"name": "ハンバーグ（生）",       "icon": "🍔", "limit": 3},
    {"name": "メンチカツ（生）",       "icon": "🍖", "limit": 3},
    {"name": "コンビーフ",             "icon": "🥩", "limit": 5},
    {"name": "ランチョンミート",       "icon": "🥓", "limit": 7},
    {"name": "スパム",                 "icon": "🥓", "limit": 7},
    {"name": "魚肉ソーセージ",         "icon": "🌭", "limit": 14},
  ],

  // ── 魚介加工品 ───────────────────────────────────────
  "魚介加工品": [
    {"name": "ちくわ",             "icon": "🍢", "limit": 5},
    {"name": "かまぼこ（白）",     "icon": "🍢", "limit": 5},
    {"name": "かまぼこ（赤）",     "icon": "🍢", "limit": 5},
    {"name": "カニカマ",           "icon": "🍢", "limit": 5},
    {"name": "さつま揚げ",         "icon": "🍢", "limit": 5},
    {"name": "はんぺん",           "icon": "🍢", "limit": 5},
    {"name": "なると",             "icon": "🍢", "limit": 5},
    {"name": "つみれ",             "icon": "🍢", "limit": 3},
    {"name": "えびしんじょ",       "icon": "🍢", "limit": 3},
    {"name": "ちくわぶ",           "icon": "🍢", "limit": 5},
    {"name": "伊達巻",             "icon": "🍢", "limit": 5},
    {"name": "たまご焼き（市販）", "icon": "🍳", "limit": 3},
    {"name": "かに風味かまぼこ",   "icon": "🍢", "limit": 5},
  ],

  // ── 鮮魚（切り身・一尾） ─────────────────────────────
  "鮮魚": [
    {"name": "鮭の切り身",         "icon": "🐟", "limit": 2},
    {"name": "鮭（一尾）",         "icon": "🐟", "limit": 2},
    {"name": "サーモン（刺身）",   "icon": "🍣", "limit": 1},
    {"name": "マグロ（赤身・刺身）","icon": "🍣", "limit": 1},
    {"name": "マグロ（中とろ・刺身）","icon": "🍣", "limit": 1},
    {"name": "マグロ（大とろ・刺身）","icon": "🍣", "limit": 1},
    {"name": "サバの切り身",       "icon": "🐟", "limit": 2},
    {"name": "サバ（一尾）",       "icon": "🐟", "limit": 2},
    {"name": "アジの切り身",       "icon": "🐟", "limit": 2},
    {"name": "アジ（一尾）",       "icon": "🐟", "limit": 2},
    {"name": "アジ（干物）",       "icon": "🐟", "limit": 7},
    {"name": "イワシの切り身",     "icon": "🐟", "limit": 2},
    {"name": "イワシ（一尾）",     "icon": "🐟", "limit": 2},
    {"name": "サンマの切り身",     "icon": "🐟", "limit": 2},
    {"name": "サンマ（一尾）",     "icon": "🐟", "limit": 2},
    {"name": "サンマ（干物）",     "icon": "🐟", "limit": 7},
    {"name": "ブリの切り身",       "icon": "🐟", "limit": 2},
    {"name": "ハマチの切り身",     "icon": "🐟", "limit": 2},
    {"name": "カレイの切り身",     "icon": "🐟", "limit": 2},
    {"name": "ヒラメの切り身",     "icon": "🐟", "limit": 2},
    {"name": "タイの切り身",       "icon": "🐟", "limit": 2},
    {"name": "タイ（一尾）",       "icon": "🐟", "limit": 2},
    {"name": "タラの切り身",       "icon": "🐟", "limit": 2},
    {"name": "サワラの切り身",     "icon": "🐟", "limit": 2},
    {"name": "カツオの切り身",     "icon": "🐟", "limit": 1},
    {"name": "カツオ（刺身）",     "icon": "🍣", "limit": 1},
    {"name": "シシャモ",           "icon": "🐟", "limit": 3},
    {"name": "ウナギ（蒲焼き）",   "icon": "🐟", "limit": 3},
    {"name": "アナゴ",             "icon": "🐟", "limit": 2},
    {"name": "キンメダイの切り身", "icon": "🐟", "limit": 2},
    {"name": "メカジキの切り身",   "icon": "🐟", "limit": 2},
    {"name": "ホッケの切り身",     "icon": "🐟", "limit": 2},
    {"name": "ホッケ（干物）",     "icon": "🐟", "limit": 7},
    {"name": "アユ（一尾）",       "icon": "🐟", "limit": 2},
    {"name": "マス（切り身）",     "icon": "🐟", "limit": 2},
    {"name": "スズキの切り身",     "icon": "🐟", "limit": 2},
    {"name": "イサキ（一尾）",     "icon": "🐟", "limit": 2},
    {"name": "メバル（一尾）",     "icon": "🐟", "limit": 2},
    {"name": "カマス（一尾）",     "icon": "🐟", "limit": 2},
    {"name": "ニシンの切り身",     "icon": "🐟", "limit": 2},
  ],

  // ── 魚卵・珍味 ───────────────────────────────────────
  "魚卵・珍味": [
    {"name": "いくら",             "icon": "🍣", "limit": 3},
    {"name": "たらこ",             "icon": "🍣", "limit": 3},
    {"name": "明太子",             "icon": "🍣", "limit": 3},
    {"name": "すじこ",             "icon": "🍣", "limit": 3},
    {"name": "とびっこ",           "icon": "🍣", "limit": 3},
    {"name": "かずのこ",           "icon": "🍣", "limit": 3},
    {"name": "シラス",             "icon": "🐟", "limit": 3},
    {"name": "しらす",             "icon": "🐟", "limit": 3},
    {"name": "ちりめんじゃこ",     "icon": "🐟", "limit": 7},
    {"name": "塩辛",               "icon": "🍣", "limit": 7},
    {"name": "うに",               "icon": "🍣", "limit": 1},
    {"name": "あん肝",             "icon": "🍣", "limit": 2},
    {"name": "くん製（スモーク）サーモン","icon": "🍣", "limit": 7},
  ],

  // ── 貝・海鮮類 ───────────────────────────────────────
  "貝・海鮮類": [
    {"name": "えび（有頭）",       "icon": "🦐", "limit": 2},
    {"name": "えび（むき身）",     "icon": "🦐", "limit": 2},
    {"name": "ブラックタイガー",   "icon": "🦐", "limit": 2},
    {"name": "甘えび",             "icon": "🦐", "limit": 1},
    {"name": "車えび",             "icon": "🦐", "limit": 2},
    {"name": "いか（丸ごと）",     "icon": "🦑", "limit": 2},
    {"name": "いか（輪切り）",     "icon": "🦑", "limit": 2},
    {"name": "するめいか",         "icon": "🦑", "limit": 2},
    {"name": "やりいか",           "icon": "🦑", "limit": 2},
    {"name": "たこ（足）",         "icon": "🐙", "limit": 2},
    {"name": "たこ（刺身）",       "icon": "🐙", "limit": 1},
    {"name": "かに（ズワイ）",     "icon": "🦀", "limit": 2},
    {"name": "かに（タラバ）",     "icon": "🦀", "limit": 2},
    {"name": "かに（毛ガニ）",     "icon": "🦀", "limit": 2},
    {"name": "ホタテ（貝柱）",     "icon": "🐚", "limit": 2},
    {"name": "ホタテ（殻付き）",   "icon": "🐚", "limit": 2},
    {"name": "アサリ（砂抜き済）", "icon": "🐚", "limit": 2},
    {"name": "シジミ",             "icon": "🐚", "limit": 2},
    {"name": "ハマグリ",           "icon": "🐚", "limit": 2},
    {"name": "カキ（殻付き）",     "icon": "🦪", "limit": 2},
    {"name": "カキ（むき身）",     "icon": "🦪", "limit": 2},
    {"name": "ムール貝",           "icon": "🐚", "limit": 2},
    {"name": "サザエ",             "icon": "🐚", "limit": 3},
    {"name": "アワビ",             "icon": "🐚", "limit": 3},
    {"name": "ホッキガイ",         "icon": "🐚", "limit": 2},
    {"name": "つぶ貝",             "icon": "🐚", "limit": 2},
  ],

  // ── 乳製品 ───────────────────────────────────────────
  "乳製品": [
    {"name": "牛乳",                   "icon": "🥛", "limit": 7},
    {"name": "低脂肪牛乳",             "icon": "🥛", "limit": 7},
    {"name": "無脂肪牛乳",             "icon": "🥛", "limit": 7},
    {"name": "豆乳（無調整）",         "icon": "🥛", "limit": 7},
    {"name": "豆乳（調整）",           "icon": "🥛", "limit": 7},
    {"name": "アーモンドミルク",       "icon": "🥛", "limit": 7},
    {"name": "オーツミルク",           "icon": "🥛", "limit": 7},
    {"name": "生クリーム",             "icon": "🥛", "limit": 7},
    {"name": "ホイップクリーム",       "icon": "🥛", "limit": 7},
    {"name": "コーヒーフレッシュ",     "icon": "🥛", "limit": 14},
    {"name": "ヨーグルト（プレーン）", "icon": "🥛", "limit": 7},
    {"name": "ヨーグルト（加糖）",     "icon": "🥛", "limit": 7},
    {"name": "ギリシャヨーグルト",     "icon": "🥛", "limit": 7},
    {"name": "飲むヨーグルト",         "icon": "🥛", "limit": 7},
    {"name": "バター（有塩）",         "icon": "🧈", "limit": 30},
    {"name": "バター（無塩）",         "icon": "🧈", "limit": 30},
    {"name": "マーガリン",             "icon": "🧈", "limit": 30},
    {"name": "サワークリーム",         "icon": "🥛", "limit": 14},
    {"name": "クレームフレーシュ",     "icon": "🥛", "limit": 7},
  ],

  // ── チーズ ───────────────────────────────────────────
  "チーズ": [
    {"name": "クリームチーズ",         "icon": "🧀", "limit": 14},
    {"name": "カマンベールチーズ",     "icon": "🧀", "limit": 14},
    {"name": "モッツァレラチーズ",     "icon": "🧀", "limit": 7},
    {"name": "チェダーチーズ",         "icon": "🧀", "limit": 21},
    {"name": "ゴーダチーズ",           "icon": "🧀", "limit": 21},
    {"name": "ブルーチーズ",           "icon": "🧀", "limit": 14},
    {"name": "ゴルゴンゾーラ",         "icon": "🧀", "limit": 14},
    {"name": "パルミジャーノ",         "icon": "🧀", "limit": 30},
    {"name": "リコッタチーズ",         "icon": "🧀", "limit": 7},
    {"name": "マスカルポーネ",         "icon": "🧀", "limit": 7},
    {"name": "スライスチーズ",         "icon": "🧀", "limit": 14},
    {"name": "6Pチーズ",               "icon": "🧀", "limit": 21},
    {"name": "粉チーズ",               "icon": "🧀", "limit": 90},
    {"name": "ハバティチーズ",         "icon": "🧀", "limit": 14},
    {"name": "エメンタールチーズ",     "icon": "🧀", "limit": 21},
    {"name": "ブリーチーズ",           "icon": "🧀", "limit": 7},
  ],

  // ── 卵 ───────────────────────────────────────────────
  "卵": [
    {"name": "鶏卵（Mサイズ）",   "icon": "🥚", "limit": 14},
    {"name": "鶏卵（Lサイズ）",   "icon": "🥚", "limit": 14},
    {"name": "鶏卵（LLサイズ）",  "icon": "🥚", "limit": 14},
    {"name": "うずらの卵",         "icon": "🥚", "limit": 14},
    {"name": "温泉卵",             "icon": "🥚", "limit": 5},
    {"name": "ゆで卵",             "icon": "🥚", "limit": 3},
    {"name": "味付けゆで卵",       "icon": "🥚", "limit": 5},
    {"name": "ピータン",           "icon": "🥚", "limit": 30},
  ],

  // ── 豆腐・大豆製品 ───────────────────────────────────
  "豆腐・大豆製品": [
    {"name": "木綿豆腐",           "icon": "🫙", "limit": 5},
    {"name": "絹ごし豆腐",         "icon": "🫙", "limit": 5},
    {"name": "充填豆腐",           "icon": "🫙", "limit": 10},
    {"name": "焼き豆腐",           "icon": "🫙", "limit": 5},
    {"name": "厚揚げ",             "icon": "🫙", "limit": 5},
    {"name": "油揚げ（薄揚げ）",   "icon": "🫙", "limit": 5},
    {"name": "がんもどき",         "icon": "🫙", "limit": 5},
    {"name": "高野豆腐",           "icon": "🫙", "limit": 365},
    {"name": "湯葉",               "icon": "🫙", "limit": 5},
    {"name": "納豆（糸引き）",     "icon": "🫙", "limit": 7},
    {"name": "納豆（ひきわり）",   "icon": "🫙", "limit": 7},
    {"name": "おから",             "icon": "🫙", "limit": 3},
    {"name": "大豆ミート",         "icon": "🫙", "limit": 5},
    {"name": "枝豆",               "icon": "🫛", "limit": 3},
    {"name": "豆乳ヨーグルト",     "icon": "🫙", "limit": 7},
    {"name": "きな粉",             "icon": "🫙", "limit": 90},
  ],

  // ── 葉物野菜 ─────────────────────────────────────────
  "葉物野菜": [
    {"name": "キャベツ（1玉）",     "icon": "🥬", "limit": 14},
    {"name": "キャベツ（カット）",  "icon": "🥬", "limit": 3},
    {"name": "紫キャベツ",          "icon": "🥬", "limit": 14},
    {"name": "レタス",              "icon": "🥬", "limit": 5},
    {"name": "サニーレタス",        "icon": "🥬", "limit": 5},
    {"name": "ロメインレタス",      "icon": "🥬", "limit": 5},
    {"name": "グリーンリーフ",      "icon": "🥬", "limit": 5},
    {"name": "白菜（1玉）",         "icon": "🥬", "limit": 14},
    {"name": "白菜（カット）",      "icon": "🥬", "limit": 3},
    {"name": "ほうれん草",          "icon": "🥬", "limit": 4},
    {"name": "小松菜",              "icon": "🥬", "limit": 4},
    {"name": "水菜",                "icon": "🥬", "limit": 5},
    {"name": "チンゲンサイ",        "icon": "🥬", "limit": 5},
    {"name": "春菊",                "icon": "🥬", "limit": 4},
    {"name": "ルッコラ",            "icon": "🥬", "limit": 3},
    {"name": "ケール",              "icon": "🥬", "limit": 5},
    {"name": "菜の花",              "icon": "🥬", "limit": 4},
    {"name": "小ねぎ（万能ねぎ）",  "icon": "🌿", "limit": 5},
    {"name": "セロリ",              "icon": "🥬", "limit": 7},
    {"name": "パセリ",              "icon": "🌿", "limit": 5},
    {"name": "大葉（しそ）",        "icon": "🌿", "limit": 5},
    {"name": "三つ葉",              "icon": "🌿", "limit": 4},
    {"name": "バジル（生）",        "icon": "🌿", "limit": 5},
    {"name": "パクチー",            "icon": "🌿", "limit": 4},
    {"name": "ミント（生）",        "icon": "🌿", "limit": 5},
    {"name": "ローズマリー（生）",  "icon": "🌿", "limit": 7},
    {"name": "タイム（生）",        "icon": "🌿", "limit": 7},
    {"name": "ディル（生）",        "icon": "🌿", "limit": 4},
    {"name": "豆苗",                "icon": "🌱", "limit": 3},
    {"name": "もやし（豆もやし）",  "icon": "🌱", "limit": 2},
    {"name": "もやし（緑豆）",      "icon": "🌱", "limit": 2},
    {"name": "ブロッコリースプラウト","icon": "🌱", "limit": 5},
    {"name": "かいわれ大根",        "icon": "🌱", "limit": 3},
  ],

  // ── 根菜 ─────────────────────────────────────────────
  "根菜": [
    {"name": "にんじん",           "icon": "🥕", "limit": 14},
    {"name": "大根（1本）",        "icon": "🥕", "limit": 14},
    {"name": "大根（カット）",     "icon": "🥕", "limit": 3},
    {"name": "ごぼう",             "icon": "🥕", "limit": 14},
    {"name": "れんこん",           "icon": "🥕", "limit": 14},
    {"name": "カブ",               "icon": "🥕", "limit": 7},
    {"name": "じゃがいも（男爵）", "icon": "🥔", "limit": 30},
    {"name": "じゃがいも（メークイン）","icon": "🥔", "limit": 30},
    {"name": "さつまいも（紅あずま）","icon": "🍠", "limit": 30},
    {"name": "さつまいも（安納芋）","icon": "🍠", "limit": 30},
    {"name": "さつまいも（紫芋）", "icon": "🍠", "limit": 30},
    {"name": "里芋",               "icon": "🥔", "limit": 14},
    {"name": "長いも",             "icon": "🥕", "limit": 14},
    {"name": "山芋",               "icon": "🥕", "limit": 14},
    {"name": "玉ねぎ",             "icon": "🧅", "limit": 30},
    {"name": "たまねぎ（白）",     "icon": "🧅", "limit": 30},
    {"name": "たまねぎ（赤）",     "icon": "🧅", "limit": 21},
    {"name": "新たまねぎ",         "icon": "🧅", "limit": 7},
    {"name": "長ねぎ",             "icon": "🧅", "limit": 7},
    {"name": "にんにく",           "icon": "🧄", "limit": 30},
    {"name": "しょうが",           "icon": "🧄", "limit": 14},
    {"name": "ニラ",               "icon": "🌿", "limit": 5},
    {"name": "わけぎ",             "icon": "🌿", "limit": 5},
    {"name": "アスパラガス（グリーン）","icon": "🥦", "limit": 4},
    {"name": "アスパラガス（ホワイト）","icon": "🥦", "limit": 4},
    {"name": "ラディッシュ",       "icon": "🥕", "limit": 5},
    {"name": "ビーツ",             "icon": "🥕", "limit": 14},
    {"name": "タケノコ（水煮）",   "icon": "🥕", "limit": 3},
  ],

  // ── 実野菜・果菜 ─────────────────────────────────────
  "実野菜": [
    {"name": "トマト",             "icon": "🍅", "limit": 7},
    {"name": "ミニトマト",         "icon": "🍅", "limit": 7},
    {"name": "中玉トマト",         "icon": "🍅", "limit": 7},
    {"name": "きゅうり",           "icon": "🥒", "limit": 7},
    {"name": "なす",               "icon": "🍆", "limit": 5},
    {"name": "ピーマン（緑）",     "icon": "🫑", "limit": 7},
    {"name": "パプリカ（赤）",     "icon": "🫑", "limit": 7},
    {"name": "パプリカ（黄）",     "icon": "🫑", "limit": 7},
    {"name": "パプリカ（オレンジ）","icon": "🫑", "limit": 7},
    {"name": "ズッキーニ（緑）",   "icon": "🥒", "limit": 5},
    {"name": "ズッキーニ（黄）",   "icon": "🥒", "limit": 5},
    {"name": "ゴーヤ",             "icon": "🥒", "limit": 5},
    {"name": "オクラ",             "icon": "🥦", "limit": 3},
    {"name": "とうもろこし",       "icon": "🌽", "limit": 3},
    {"name": "かぼちゃ（西洋）",   "icon": "🎃", "limit": 30},
    {"name": "かぼちゃ（日本）",   "icon": "🎃", "limit": 30},
    {"name": "ブロッコリー",       "icon": "🥦", "limit": 5},
    {"name": "カリフラワー",       "icon": "🥦", "limit": 7},
    {"name": "スナップえんどう",   "icon": "🫛", "limit": 4},
    {"name": "さやいんげん",       "icon": "🫛", "limit": 4},
    {"name": "さやえんどう",       "icon": "🫛", "limit": 4},
    {"name": "そら豆",             "icon": "🫛", "limit": 3},
    {"name": "グリーンピース",     "icon": "🫛", "limit": 3},
    {"name": "アボカド",           "icon": "🥑", "limit": 3},
    {"name": "とうがらし（赤）",   "icon": "🌶️", "limit": 7},
    {"name": "とうがらし（青）",   "icon": "🌶️", "limit": 7},
    {"name": "しし唐",             "icon": "🫑", "limit": 5},
    {"name": "芽キャベツ",         "icon": "🥦", "limit": 5},
    {"name": "プチヴェール",       "icon": "🥦", "limit": 5},
    {"name": "ロマネスコ",         "icon": "🥦", "limit": 5},
  ],

  // ── きのこ類 ─────────────────────────────────────────
  "きのこ類": [
    {"name": "しいたけ（生）",         "icon": "🍄", "limit": 5},
    {"name": "しいたけ（乾燥）",       "icon": "🍄", "limit": 365},
    {"name": "しめじ（ぶなしめじ）",   "icon": "🍄", "limit": 5},
    {"name": "えのき",                 "icon": "🍄", "limit": 5},
    {"name": "まいたけ",               "icon": "🍄", "limit": 5},
    {"name": "エリンギ",               "icon": "🍄", "limit": 7},
    {"name": "なめこ",                 "icon": "🍄", "limit": 5},
    {"name": "マッシュルーム（白）",   "icon": "🍄", "limit": 5},
    {"name": "マッシュルーム（茶）",   "icon": "🍄", "limit": 5},
    {"name": "松茸",                   "icon": "🍄", "limit": 3},
    {"name": "キクラゲ（生）",         "icon": "🍄", "limit": 3},
    {"name": "キクラゲ（乾燥）",       "icon": "🍄", "limit": 365},
    {"name": "ひらたけ",               "icon": "🍄", "limit": 5},
    {"name": "なめたけ（瓶詰）",       "icon": "🍄", "limit": 90},
  ],

  // ── 海藻類 ───────────────────────────────────────────
  "海藻類": [
    {"name": "わかめ（生）",       "icon": "🌊", "limit": 3},
    {"name": "わかめ（乾燥）",     "icon": "🌊", "limit": 365},
    {"name": "昆布（乾燥）",       "icon": "🌊", "limit": 365},
    {"name": "もずく",             "icon": "🌊", "limit": 14},
    {"name": "めかぶ",             "icon": "🌊", "limit": 5},
    {"name": "ひじき（乾燥）",     "icon": "🌊", "limit": 365},
    {"name": "焼きのり",           "icon": "🌊", "limit": 90},
    {"name": "味付けのり",         "icon": "🌊", "limit": 90},
    {"name": "とろろ昆布",         "icon": "🌊", "limit": 90},
    {"name": "塩昆布",             "icon": "🌊", "limit": 90},
    {"name": "アオサ（乾燥）",     "icon": "🌊", "limit": 365},
  ],

  // ── 果物 ─────────────────────────────────────────────
  "果物": [
    {"name": "りんご（ふじ）",         "icon": "🍎", "limit": 14},
    {"name": "りんご（つがる）",       "icon": "🍎", "limit": 14},
    {"name": "りんご（王林）",         "icon": "🍏", "limit": 14},
    {"name": "みかん",                 "icon": "🍊", "limit": 7},
    {"name": "オレンジ",               "icon": "🍊", "limit": 7},
    {"name": "グレープフルーツ（赤）", "icon": "🍊", "limit": 7},
    {"name": "グレープフルーツ（白）", "icon": "🍊", "limit": 7},
    {"name": "レモン",                 "icon": "🍋", "limit": 14},
    {"name": "ゆず",                   "icon": "🍋", "limit": 14},
    {"name": "シークワーサー",         "icon": "🍋", "limit": 14},
    {"name": "カボス",                 "icon": "🍋", "limit": 14},
    {"name": "すだち",                 "icon": "🍋", "limit": 14},
    {"name": "バナナ",                 "icon": "🍌", "limit": 5},
    {"name": "ぶどう（巨峰）",         "icon": "🍇", "limit": 5},
    {"name": "ぶどう（デラウェア）",   "icon": "🍇", "limit": 5},
    {"name": "マスカット",             "icon": "🍇", "limit": 5},
    {"name": "シャインマスカット",     "icon": "🍇", "limit": 7},
    {"name": "いちご",                 "icon": "🍓", "limit": 3},
    {"name": "ブルーベリー",           "icon": "🫐", "limit": 3},
    {"name": "ラズベリー",             "icon": "🍓", "limit": 2},
    {"name": "クランベリー",           "icon": "🍓", "limit": 3},
    {"name": "桃（白桃）",             "icon": "🍑", "limit": 4},
    {"name": "桃（黄桃）",             "icon": "🍑", "limit": 4},
    {"name": "スイカ",                 "icon": "🍉", "limit": 5},
    {"name": "スイカ（カット）",       "icon": "🍉", "limit": 2},
    {"name": "メロン",                 "icon": "🍈", "limit": 5},
    {"name": "梨（幸水）",             "icon": "🍐", "limit": 7},
    {"name": "梨（豊水）",             "icon": "🍐", "limit": 7},
    {"name": "柿（富有柿）",           "icon": "🍊", "limit": 7},
    {"name": "柿（次郎柿）",           "icon": "🍊", "limit": 7},
    {"name": "キウイ（グリーン）",     "icon": "🥝", "limit": 7},
    {"name": "キウイ（ゴールド）",     "icon": "🥝", "limit": 7},
    {"name": "パイナップル",           "icon": "🍍", "limit": 5},
    {"name": "マンゴー",               "icon": "🥭", "limit": 5},
    {"name": "パパイヤ",               "icon": "🥭", "limit": 4},
    {"name": "さくらんぼ",             "icon": "🍒", "limit": 3},
    {"name": "プラム",                 "icon": "🍑", "limit": 4},
    {"name": "プルーン",               "icon": "🍑", "limit": 4},
    {"name": "梅",                     "icon": "🍋", "limit": 3},
    {"name": "いちじく",               "icon": "🍊", "limit": 3},
    {"name": "ライチ",                 "icon": "🍊", "limit": 3},
    {"name": "ドラゴンフルーツ",       "icon": "🍓", "limit": 5},
    {"name": "ザクロ",                 "icon": "🍓", "limit": 7},
    {"name": "ネクタリン",             "icon": "🍑", "limit": 4},
    {"name": "びわ",                   "icon": "🍊", "limit": 3},
    {"name": "すもも",                 "icon": "🍑", "limit": 3},
    {"name": "グアバ",                 "icon": "🍊", "limit": 4},
  ],

  // ── 米・雑穀 ─────────────────────────────────────────
  "米・雑穀": [
    {"name": "白米（コシヒカリ）",     "icon": "🍚", "limit": 14},
    {"name": "白米（あきたこまち）",   "icon": "🍚", "limit": 14},
    {"name": "白米（ひとめぼれ）",     "icon": "🍚", "limit": 14},
    {"name": "白米（ゆめぴりか）",     "icon": "🍚", "limit": 14},
    {"name": "無洗米",                 "icon": "🍚", "limit": 14},
    {"name": "玄米",                   "icon": "🍚", "limit": 14},
    {"name": "冷凍ご飯",               "icon": "🍚", "limit": 30},
    {"name": "もち米",                 "icon": "🍚", "limit": 14},
    {"name": "もち麦",                 "icon": "🍚", "limit": 90},
    {"name": "押し麦",                 "icon": "🍚", "limit": 90},
    {"name": "雑穀米ミックス",         "icon": "🍚", "limit": 90},
    {"name": "オートミール",           "icon": "🥣", "limit": 90},
    {"name": "コーンフレーク",         "icon": "🥣", "limit": 90},
    {"name": "グラノーラ",             "icon": "🥣", "limit": 90},
    {"name": "パックご飯",             "icon": "🍚", "limit": 180},
  ],

  // ── 麺類 ─────────────────────────────────────────────
  "麺類": [
    {"name": "うどん（生）",           "icon": "🍜", "limit": 5},
    {"name": "うどん（冷凍）",         "icon": "🍜", "limit": 60},
    {"name": "うどん（乾燥）",         "icon": "🍜", "limit": 730},
    {"name": "そば（生）",             "icon": "🍜", "limit": 5},
    {"name": "そば（乾燥）",           "icon": "🍜", "limit": 730},
    {"name": "ラーメン（生）",         "icon": "🍜", "limit": 5},
    {"name": "ラーメン（乾燥）",       "icon": "🍜", "limit": 365},
    {"name": "中華麺（生）",           "icon": "🍜", "limit": 5},
    {"name": "焼きそば麺",             "icon": "🍜", "limit": 5},
    {"name": "パスタ（スパゲティ）",   "icon": "🍝", "limit": 730},
    {"name": "パスタ（ペンネ）",       "icon": "🍝", "limit": 730},
    {"name": "パスタ（フェットチーネ）","icon": "🍝", "limit": 730},
    {"name": "パスタ（生）",           "icon": "🍝", "limit": 5},
    {"name": "そうめん",               "icon": "🍜", "limit": 730},
    {"name": "ひやむぎ",               "icon": "🍜", "limit": 730},
    {"name": "ビーフン",               "icon": "🍜", "limit": 365},
    {"name": "フォー",                 "icon": "🍜", "limit": 365},
    {"name": "春雨（乾燥）",           "icon": "🍜", "limit": 365},
    {"name": "餃子の皮",               "icon": "🥟", "limit": 5},
    {"name": "春巻きの皮",             "icon": "🥟", "limit": 5},
    {"name": "ワンタンの皮",           "icon": "🥟", "limit": 5},
    {"name": "シュウマイの皮",         "icon": "🥟", "limit": 5},
  ],

  // ── パン類 ───────────────────────────────────────────
  "パン類": [
    {"name": "食パン（6枚切り）",     "icon": "🍞", "limit": 5},
    {"name": "食パン（8枚切り）",     "icon": "🍞", "limit": 5},
    {"name": "食パン（4枚切り）",     "icon": "🍞", "limit": 5},
    {"name": "ロールパン",             "icon": "🍞", "limit": 3},
    {"name": "バゲット",               "icon": "🥖", "limit": 3},
    {"name": "クロワッサン",           "icon": "🥐", "limit": 3},
    {"name": "ベーグル",               "icon": "🥯", "limit": 3},
    {"name": "イングリッシュマフィン", "icon": "🥯", "limit": 3},
    {"name": "ピタパン",               "icon": "🫓", "limit": 3},
    {"name": "ナン",                   "icon": "🫓", "limit": 3},
    {"name": "米粉パン",               "icon": "🍞", "limit": 3},
    {"name": "全粒粉パン",             "icon": "🍞", "limit": 5},
    {"name": "ライ麦パン",             "icon": "🍞", "limit": 5},
    {"name": "メロンパン",             "icon": "🍞", "limit": 3},
    {"name": "あんぱん",               "icon": "🍞", "limit": 3},
    {"name": "クリームパン",           "icon": "🍞", "limit": 3},
    {"name": "コッペパン",             "icon": "🍞", "limit": 3},
    {"name": "カレーパン",             "icon": "🍞", "limit": 3},
    {"name": "惣菜パン",               "icon": "🍞", "limit": 2},
    {"name": "デニッシュ",             "icon": "🥐", "limit": 3},
    {"name": "スコーン",               "icon": "🥐", "limit": 3},
    {"name": "ホットドッグ用パン",     "icon": "🌭", "limit": 3},
    {"name": "ハンバーガーバンズ",     "icon": "🍔", "limit": 3},
  ],

  // ── 冷凍食品 ─────────────────────────────────────────
  "冷凍食品": [
    {"name": "冷凍餃子",               "icon": "🥟", "limit": 60},
    {"name": "冷凍シューマイ",         "icon": "🥟", "limit": 60},
    {"name": "冷凍春巻き",             "icon": "🥟", "limit": 60},
    {"name": "冷凍唐揚げ",             "icon": "🍗", "limit": 60},
    {"name": "冷凍エビフライ",         "icon": "🍤", "limit": 60},
    {"name": "冷凍コロッケ",           "icon": "🍤", "limit": 60},
    {"name": "冷凍ハンバーグ",         "icon": "🍔", "limit": 60},
    {"name": "冷凍メンチカツ",         "icon": "🍔", "limit": 60},
    {"name": "冷凍とんかつ",           "icon": "🍖", "limit": 60},
    {"name": "冷凍たこ焼き",           "icon": "🐙", "limit": 60},
    {"name": "冷凍お好み焼き",         "icon": "🥞", "limit": 60},
    {"name": "冷凍ピザ",               "icon": "🍕", "limit": 60},
    {"name": "冷凍炒飯",               "icon": "🍚", "limit": 60},
    {"name": "冷凍ピラフ",             "icon": "🍚", "limit": 60},
    {"name": "冷凍おにぎり",           "icon": "🍙", "limit": 60},
    {"name": "冷凍うどん",             "icon": "🍜", "limit": 60},
    {"name": "冷凍ラーメン",           "icon": "🍜", "limit": 60},
    {"name": "冷凍パスタ",             "icon": "🍝", "limit": 60},
    {"name": "冷凍グラタン",           "icon": "🍲", "limit": 60},
    {"name": "冷凍肉まん",             "icon": "🥟", "limit": 60},
    {"name": "冷凍あんまん",           "icon": "🥟", "limit": 60},
    {"name": "冷凍えび",               "icon": "🦐", "limit": 60},
    {"name": "冷凍ホタテ",             "icon": "🐚", "limit": 60},
    {"name": "冷凍いか",               "icon": "🦑", "limit": 60},
    {"name": "冷凍シーフードミックス", "icon": "🦐", "limit": 60},
    {"name": "冷凍ブロッコリー",       "icon": "🥦", "limit": 60},
    {"name": "冷凍ほうれん草",         "icon": "🥬", "limit": 60},
    {"name": "冷凍枝豆",               "icon": "🫛", "limit": 60},
    {"name": "冷凍コーン",             "icon": "🌽", "limit": 60},
    {"name": "冷凍ミックスベジタブル", "icon": "🥦", "limit": 60},
    {"name": "冷凍かぼちゃ",           "icon": "🎃", "limit": 60},
    {"name": "冷凍いちご",             "icon": "🍓", "limit": 60},
    {"name": "冷凍マンゴー",           "icon": "🥭", "limit": 60},
    {"name": "冷凍ブルーベリー",       "icon": "🫐", "limit": 60},
    {"name": "冷凍アイスクリーム",     "icon": "🍦", "limit": 60},
  ],

  // ── レトルト・インスタント ───────────────────────────
  "レトルト・インスタント": [
    {"name": "カレー（レトルト）",         "icon": "🍛", "limit": 730},
    {"name": "ハヤシライス（レトルト）",   "icon": "🍛", "limit": 730},
    {"name": "ビーフシチュー（レトルト）", "icon": "🍲", "limit": 730},
    {"name": "クリームシチュー（レトルト）","icon": "🍲", "limit": 730},
    {"name": "麻婆豆腐の素",               "icon": "🍲", "limit": 365},
    {"name": "八宝菜の素",                 "icon": "🍲", "limit": 365},
    {"name": "酢豚の素",                   "icon": "🍲", "limit": 365},
    {"name": "回鍋肉の素",                 "icon": "🍲", "limit": 365},
    {"name": "親子丼の素",                 "icon": "🍲", "limit": 365},
    {"name": "牛丼の素",                   "icon": "🍲", "limit": 365},
    {"name": "中華丼の素",                 "icon": "🍲", "limit": 365},
    {"name": "パスタソース（ミートソース）","icon": "🍝", "limit": 730},
    {"name": "パスタソース（カルボナーラ）","icon": "🍝", "limit": 730},
    {"name": "パスタソース（ペペロンチーノ）","icon": "🍝", "limit": 730},
    {"name": "パスタソース（ナポリタン）", "icon": "🍝", "limit": 730},
    {"name": "インスタント味噌汁",         "icon": "🍵", "limit": 365},
    {"name": "インスタントラーメン",       "icon": "🍜", "limit": 365},
    {"name": "インスタントうどん",         "icon": "🍜", "limit": 365},
    {"name": "カップラーメン",             "icon": "🍜", "limit": 180},
    {"name": "カップうどん",               "icon": "🍜", "limit": 180},
    {"name": "カップ焼きそば",             "icon": "🍜", "limit": 180},
    {"name": "おでんセット",               "icon": "🍢", "limit": 30},
    {"name": "鍋つゆ（寄せ鍋）",           "icon": "🍲", "limit": 365},
    {"name": "鍋つゆ（すき焼き）",         "icon": "🍲", "limit": 365},
    {"name": "鍋つゆ（しゃぶしゃぶ）",     "icon": "🍲", "limit": 365},
    {"name": "鍋つゆ（豆乳鍋）",           "icon": "🍲", "limit": 365},
    {"name": "鍋つゆ（キムチ鍋）",         "icon": "🍲", "limit": 365},
    {"name": "鍋つゆ（トマト鍋）",         "icon": "🍲", "limit": 365},
    {"name": "アルファ米",                 "icon": "🍚", "limit": 1825},
  ],

  // ── 缶詰 ─────────────────────────────────────────────
  "缶詰": [
    {"name": "ツナ缶（水煮）",         "icon": "🥫", "limit": 1095},
    {"name": "ツナ缶（油漬け）",       "icon": "🥫", "limit": 1095},
    {"name": "サバ缶（水煮）",         "icon": "🥫", "limit": 1095},
    {"name": "サバ缶（味噌煮）",       "icon": "🥫", "limit": 1095},
    {"name": "サバ缶（醤油煮）",       "icon": "🥫", "limit": 1095},
    {"name": "イワシ缶（水煮）",       "icon": "🥫", "limit": 1095},
    {"name": "イワシ缶（蒲焼き）",     "icon": "🥫", "limit": 1095},
    {"name": "サーモン缶",             "icon": "🥫", "limit": 1095},
    {"name": "カニ缶",                 "icon": "🥫", "limit": 1095},
    {"name": "ホタテ缶",               "icon": "🥫", "limit": 1095},
    {"name": "アサリ缶",               "icon": "🥫", "limit": 1095},
    {"name": "焼き鳥缶（塩）",         "icon": "🥫", "limit": 1095},
    {"name": "焼き鳥缶（たれ）",       "icon": "🥫", "limit": 1095},
    {"name": "コンビーフ缶",           "icon": "🥫", "limit": 1095},
    {"name": "ランチョンミート缶",     "icon": "🥫", "limit": 1095},
    {"name": "コーン缶",               "icon": "🥫", "limit": 1095},
    {"name": "トマト缶（ホール）",     "icon": "🥫", "limit": 1095},
    {"name": "トマト缶（カット）",     "icon": "🥫", "limit": 1095},
    {"name": "大豆缶",                 "icon": "🥫", "limit": 1095},
    {"name": "ひよこ豆缶",             "icon": "🥫", "limit": 1095},
    {"name": "ミックスビーンズ缶",     "icon": "🥫", "limit": 1095},
    {"name": "フルーツ缶（みかん）",   "icon": "🥫", "limit": 1095},
    {"name": "フルーツ缶（黄桃）",     "icon": "🥫", "limit": 1095},
    {"name": "フルーツ缶（パイン）",   "icon": "🥫", "limit": 1095},
    {"name": "コーンスープ缶",         "icon": "🥫", "limit": 1095},
    {"name": "クラムチャウダー缶",     "icon": "🥫", "limit": 1095},
  ],

  // ── ジャム・スプレッド・瓶詰め ──────────────────────
  "ジャム・スプレッド": [
    {"name": "いちごジャム",           "icon": "🫙", "limit": 180},
    {"name": "ブルーベリージャム",     "icon": "🫙", "limit": 180},
    {"name": "マーマレード",           "icon": "🫙", "limit": 180},
    {"name": "りんごジャム",           "icon": "🫙", "limit": 180},
    {"name": "あんずジャム",           "icon": "🫙", "limit": 180},
    {"name": "ラズベリージャム",       "icon": "🫙", "limit": 180},
    {"name": "ぶどうジャム",           "icon": "🫙", "limit": 180},
    {"name": "ピーナッツバター（有糖）","icon": "🫙", "limit": 180},
    {"name": "ピーナッツバター（無糖）","icon": "🫙", "limit": 180},
    {"name": "アーモンドバター",       "icon": "🫙", "limit": 180},
    {"name": "チョコレートスプレッド", "icon": "🫙", "limit": 180},
    {"name": "はちみつ",               "icon": "🫙", "limit": 730},
    {"name": "メープルシロップ",       "icon": "🫙", "limit": 365},
    {"name": "練乳",                   "icon": "🫙", "limit": 180},
    {"name": "粒あん",                 "icon": "🫙", "limit": 7},
    {"name": "こしあん",               "icon": "🫙", "limit": 7},
    {"name": "白あん",                 "icon": "🫙", "limit": 7},
    {"name": "オリーブ（瓶）",         "icon": "🫙", "limit": 180},
    {"name": "ケイパー（瓶）",         "icon": "🫙", "limit": 180},
  ],

  // ── 漬物・発酵食品 ───────────────────────────────────
  "漬物・発酵食品": [
    {"name": "キムチ（白菜）",     "icon": "🥬", "limit": 14},
    {"name": "キムチ（大根）",     "icon": "🥬", "limit": 14},
    {"name": "キムチ（きゅうり）", "icon": "🥬", "limit": 7},
    {"name": "たくあん",           "icon": "🥒", "limit": 14},
    {"name": "ぬか漬け",           "icon": "🥒", "limit": 5},
    {"name": "浅漬け",             "icon": "🥒", "limit": 3},
    {"name": "しば漬け",           "icon": "🥒", "limit": 14},
    {"name": "梅干し",             "icon": "🍋", "limit": 365},
    {"name": "はちみつ梅",         "icon": "🍋", "limit": 365},
    {"name": "らっきょう",         "icon": "🧅", "limit": 90},
    {"name": "福神漬け",           "icon": "🥒", "limit": 30},
    {"name": "野沢菜漬け",         "icon": "🥬", "limit": 14},
    {"name": "高菜漬け",           "icon": "🥬", "limit": 14},
    {"name": "べったら漬け",       "icon": "🥒", "limit": 7},
    {"name": "千枚漬け",           "icon": "🥒", "limit": 7},
    {"name": "ザワークラウト",     "icon": "🥬", "limit": 14},
    {"name": "海苔の佃煮",         "icon": "🌊", "limit": 14},
    {"name": "昆布の佃煮",         "icon": "🌊", "limit": 14},
  ],

  // ── 調味料（液体） ───────────────────────────────────
  "調味料（液体）": [
    {"name": "濃口醤油",               "icon": "🫙", "limit": 180},
    {"name": "薄口醤油",               "icon": "🫙", "limit": 180},
    {"name": "たまり醤油",             "icon": "🫙", "limit": 180},
    {"name": "だし醤油",               "icon": "🫙", "limit": 90},
    {"name": "減塩醤油",               "icon": "🫙", "limit": 180},
    {"name": "白だし",                 "icon": "🫙", "limit": 90},
    {"name": "めんつゆ（2倍濃縮）",    "icon": "🫙", "limit": 90},
    {"name": "めんつゆ（3倍濃縮）",    "icon": "🫙", "limit": 90},
    {"name": "ポン酢",                 "icon": "🫙", "limit": 90},
    {"name": "みりん（本みりん）",     "icon": "🫙", "limit": 180},
    {"name": "みりん風調味料",         "icon": "🫙", "limit": 180},
    {"name": "料理酒",                 "icon": "🫙", "limit": 180},
    {"name": "酢（穀物酢）",           "icon": "🫙", "limit": 365},
    {"name": "米酢",                   "icon": "🫙", "limit": 365},
    {"name": "黒酢",                   "icon": "🫙", "limit": 365},
    {"name": "バルサミコ酢",           "icon": "🫙", "limit": 365},
    {"name": "ワインビネガー（赤）",   "icon": "🫙", "limit": 365},
    {"name": "ワインビネガー（白）",   "icon": "🫙", "limit": 365},
    {"name": "リンゴ酢",               "icon": "🫙", "limit": 365},
    {"name": "オイスターソース",       "icon": "🫙", "limit": 180},
    {"name": "ナンプラー",             "icon": "🫙", "limit": 180},
    {"name": "スイートチリソース",     "icon": "🫙", "limit": 180},
    {"name": "テリヤキソース",         "icon": "🫙", "limit": 180},
    {"name": "焼肉のたれ",             "icon": "🫙", "limit": 180},
    {"name": "すき焼きのたれ",         "icon": "🫙", "limit": 180},
    {"name": "ごまだれ",               "icon": "🫙", "limit": 90},
    {"name": "ドレッシング（和風）",   "icon": "🫙", "limit": 90},
    {"name": "ドレッシング（イタリアン）","icon": "🫙", "limit": 90},
    {"name": "ドレッシング（シーザー）","icon": "🫙", "limit": 90},
    {"name": "ドレッシング（青じそ）", "icon": "🫙", "limit": 90},
    {"name": "ごま油",                 "icon": "🫙", "limit": 180},
    {"name": "オリーブオイル",         "icon": "🫙", "limit": 365},
    {"name": "サラダ油",               "icon": "🫙", "limit": 365},
    {"name": "米油",                   "icon": "🫙", "limit": 365},
    {"name": "ラー油",                 "icon": "🫙", "limit": 180},
    {"name": "ウスターソース",         "icon": "🫙", "limit": 180},
    {"name": "中濃ソース",             "icon": "🫙", "limit": 180},
    {"name": "お好みソース",           "icon": "🫙", "limit": 180},
    {"name": "とんかつソース",         "icon": "🫙", "limit": 180},
    {"name": "ケチャップ",             "icon": "🍅", "limit": 180},
    {"name": "マヨネーズ",             "icon": "🫙", "limit": 90},
    {"name": "タルタルソース",         "icon": "🫙", "limit": 30},
    {"name": "マスタード（粒）",       "icon": "🫙", "limit": 90},
    {"name": "マスタード（フレンチ）", "icon": "🫙", "limit": 90},
    {"name": "豆板醤",                 "icon": "🫙", "limit": 180},
    {"name": "甜麺醤",                 "icon": "🫙", "limit": 180},
    {"name": "コチュジャン",           "icon": "🫙", "limit": 180},
    {"name": "タバスコ",               "icon": "🫙", "limit": 365},
    {"name": "スリラチャソース",       "icon": "🫙", "limit": 180},
    {"name": "バーベキューソース",     "icon": "🫙", "limit": 180},
    {"name": "カレーペースト",         "icon": "🫙", "limit": 90},
  ],

  // ── 調味料（固体・粉） ───────────────────────────────
  "調味料（固体・粉）": [
    {"name": "塩（食塩）",             "icon": "🫙", "limit": 1825},
    {"name": "岩塩",                   "icon": "🫙", "limit": 1825},
    {"name": "砂糖（上白糖）",         "icon": "🫙", "limit": 1825},
    {"name": "砂糖（グラニュー糖）",   "icon": "🫙", "limit": 1825},
    {"name": "三温糖",                 "icon": "🫙", "limit": 1825},
    {"name": "黒砂糖",                 "icon": "🫙", "limit": 1825},
    {"name": "きび砂糖",               "icon": "🫙", "limit": 1825},
    {"name": "胡椒（ブラック）",       "icon": "🫙", "limit": 365},
    {"name": "胡椒（ホワイト）",       "icon": "🫙", "limit": 365},
    {"name": "七味唐辛子",             "icon": "🫙", "limit": 365},
    {"name": "一味唐辛子",             "icon": "🫙", "limit": 365},
    {"name": "山椒",                   "icon": "🫙", "limit": 365},
    {"name": "カレー粉",               "icon": "🫙", "limit": 365},
    {"name": "クミン",                 "icon": "🫙", "limit": 365},
    {"name": "ターメリック",           "icon": "🫙", "limit": 365},
    {"name": "コリアンダー",           "icon": "🫙", "limit": 365},
    {"name": "ガラムマサラ",           "icon": "🫙", "limit": 365},
    {"name": "シナモン",               "icon": "🫙", "limit": 365},
    {"name": "ナツメグ",               "icon": "🫙", "limit": 365},
    {"name": "ローリエ（乾燥）",       "icon": "🌿", "limit": 365},
    {"name": "バジル（乾燥）",         "icon": "🌿", "limit": 365},
    {"name": "オレガノ（乾燥）",       "icon": "🌿", "limit": 365},
    {"name": "タイム（乾燥）",         "icon": "🌿", "limit": 365},
    {"name": "ローズマリー（乾燥）",   "icon": "🌿", "limit": 365},
    {"name": "鶏がらスープの素",       "icon": "🫙", "limit": 365},
    {"name": "コンソメ（固形）",       "icon": "🫙", "limit": 365},
    {"name": "コンソメ（顆粒）",       "icon": "🫙", "limit": 365},
    {"name": "だしの素",               "icon": "🫙", "limit": 365},
    {"name": "顆粒だし",               "icon": "🫙", "limit": 365},
    {"name": "かつおだし（顆粒）",     "icon": "🫙", "limit": 365},
    {"name": "昆布だし（顆粒）",       "icon": "🫙", "limit": 365},
    {"name": "味の素",                 "icon": "🫙", "limit": 365},
    {"name": "かつお節",               "icon": "🐟", "limit": 90},
    {"name": "いりごま（白）",         "icon": "🫙", "limit": 90},
    {"name": "いりごま（黒）",         "icon": "🫙", "limit": 90},
    {"name": "すりごま",               "icon": "🫙", "limit": 90},
    {"name": "わさび（チューブ）",     "icon": "🫙", "limit": 30},
    {"name": "からし（チューブ）",     "icon": "🫙", "limit": 30},
    {"name": "しょうが（チューブ）",   "icon": "🫙", "limit": 30},
    {"name": "にんにく（チューブ）",   "icon": "🫙", "limit": 30},
    {"name": "味噌（赤）",             "icon": "🫙", "limit": 90},
    {"name": "味噌（白）",             "icon": "🫙", "limit": 90},
    {"name": "味噌（合わせ）",         "icon": "🫙", "limit": 90},
    {"name": "小麦粉（薄力粉）",       "icon": "🫙", "limit": 365},
    {"name": "小麦粉（強力粉）",       "icon": "🫙", "limit": 365},
    {"name": "片栗粉",                 "icon": "🫙", "limit": 365},
    {"name": "コーンスターチ",         "icon": "🫙", "limit": 365},
    {"name": "ベーキングパウダー",     "icon": "🫙", "limit": 365},
    {"name": "パン粉",                 "icon": "🫙", "limit": 90},
    {"name": "天ぷら粉",               "icon": "🫙", "limit": 365},
    {"name": "から揚げ粉",             "icon": "🫙", "limit": 365},
    {"name": "ホットケーキミックス",   "icon": "🫙", "limit": 365},
  ],

  // ── 飲み物 ───────────────────────────────────────────
  "飲み物": [
    {"name": "ミネラルウォーター",     "icon": "💧", "limit": 365},
    {"name": "炭酸水",                 "icon": "💧", "limit": 30},
    {"name": "緑茶（ペット）",         "icon": "🍵", "limit": 7},
    {"name": "麦茶（ペット）",         "icon": "🍵", "limit": 7},
    {"name": "烏龍茶（ペット）",       "icon": "🍵", "limit": 7},
    {"name": "紅茶（ペット）",         "icon": "🫖", "limit": 7},
    {"name": "ほうじ茶（ペット）",     "icon": "🍵", "limit": 7},
    {"name": "コーヒー（ペット）",     "icon": "☕", "limit": 7},
    {"name": "カフェラテ（ペット）",   "icon": "☕", "limit": 7},
    {"name": "コーヒー（缶）",         "icon": "☕", "limit": 30},
    {"name": "オレンジジュース",       "icon": "🧃", "limit": 7},
    {"name": "りんごジュース",         "icon": "🧃", "limit": 7},
    {"name": "野菜ジュース",           "icon": "🧃", "limit": 7},
    {"name": "トマトジュース",         "icon": "🧃", "limit": 7},
    {"name": "乳酸菌飲料",             "icon": "🥛", "limit": 14},
    {"name": "コーラ",                 "icon": "🥤", "limit": 30},
    {"name": "サイダー",               "icon": "🥤", "limit": 30},
    {"name": "スポーツドリンク",       "icon": "🥤", "limit": 14},
    {"name": "エナジードリンク",       "icon": "🥤", "limit": 90},
    {"name": "ビール",                 "icon": "🍺", "limit": 90},
    {"name": "発泡酒",                 "icon": "🍺", "limit": 90},
    {"name": "第三のビール",           "icon": "🍺", "limit": 90},
    {"name": "チューハイ（レモン）",   "icon": "🍺", "limit": 90},
    {"name": "チューハイ（グレープフルーツ）","icon": "🍺", "limit": 90},
    {"name": "日本酒",                 "icon": "🍶", "limit": 90},
    {"name": "ワイン（赤）",           "icon": "🍷", "limit": 90},
    {"name": "ワイン（白）",           "icon": "🍷", "limit": 90},
    {"name": "梅酒",                   "icon": "🍶", "limit": 365},
    {"name": "焼酎",                   "icon": "🍶", "limit": 365},
  ],

  // ── お菓子・デザート ─────────────────────────────────
  "お菓子・デザート": [
    {"name": "プリン",                 "icon": "🍮", "limit": 7},
    {"name": "ゼリー",                 "icon": "🍮", "limit": 7},
    {"name": "杏仁豆腐",               "icon": "🍮", "limit": 5},
    {"name": "ムース",                 "icon": "🍮", "limit": 3},
    {"name": "シュークリーム",         "icon": "🍰", "limit": 2},
    {"name": "エクレア",               "icon": "🍰", "limit": 2},
    {"name": "ケーキ（ショートケーキ）","icon": "🎂", "limit": 3},
    {"name": "チーズケーキ",           "icon": "🍰", "limit": 3},
    {"name": "ガトーショコラ",         "icon": "🍰", "limit": 3},
    {"name": "モンブラン",             "icon": "🍰", "limit": 2},
    {"name": "ロールケーキ",           "icon": "🍰", "limit": 3},
    {"name": "タルト",                 "icon": "🍰", "limit": 3},
    {"name": "マカロン",               "icon": "🍪", "limit": 5},
    {"name": "フィナンシェ",           "icon": "🍪", "limit": 5},
    {"name": "マドレーヌ",             "icon": "🍪", "limit": 5},
    {"name": "クッキー",               "icon": "🍪", "limit": 30},
    {"name": "板チョコ（ミルク）",     "icon": "🍫", "limit": 90},
    {"name": "板チョコ（ビター）",     "icon": "🍫", "limit": 90},
    {"name": "板チョコ（ホワイト）",   "icon": "🍫", "limit": 90},
    {"name": "大福（つぶあん）",       "icon": "🍡", "limit": 3},
    {"name": "大福（いちご）",         "icon": "🍡", "limit": 3},
    {"name": "みたらし団子",           "icon": "🍡", "limit": 2},
    {"name": "どら焼き",               "icon": "🍡", "limit": 3},
    {"name": "わらび餅",               "icon": "🍡", "limit": 3},
    {"name": "くずもち",               "icon": "🍡", "limit": 2},
    {"name": "羊羹（練り）",           "icon": "🍡", "limit": 14},
    {"name": "羊羹（水）",             "icon": "🍡", "limit": 5},
    {"name": "せんべい",               "icon": "🍘", "limit": 90},
    {"name": "おかき",                 "icon": "🍘", "limit": 90},
    {"name": "ポテトチップス",         "icon": "🥔", "limit": 90},
    {"name": "グミ",                   "icon": "🍬", "limit": 90},
    {"name": "キャンディー",           "icon": "🍬", "limit": 90},
    {"name": "アイスクリーム",         "icon": "🍦", "limit": 60},
    {"name": "アイスバー",             "icon": "🍦", "limit": 60},
    {"name": "シャーベット",           "icon": "🍧", "limit": 60},
  ],
};