// 食材マスターデータ：カテゴリ、食材名、アイコン、消費期限(日)を定義
final Map<String, List<Map<String, dynamic>>> foodMaster = {

  // ── 肉類 ──────────────────────────────────────────────
  "肉類": [
    {"name": "鶏むね肉",       "icon": "🍗", "limit": 2},
    {"name": "鶏もも肉",       "icon": "🍗", "limit": 2},
    {"name": "鶏ささみ",       "icon": "🍗", "limit": 2},
    {"name": "鶏皮",           "icon": "🍗", "limit": 2},
    {"name": "手羽先",         "icon": "🍗", "limit": 2},
    {"name": "手羽元",         "icon": "🍗", "limit": 2},
    {"name": "手羽中",         "icon": "🍗", "limit": 2},
    {"name": "鶏レバー",       "icon": "🍗", "limit": 2},
    {"name": "砂肝",           "icon": "🍗", "limit": 2},
    {"name": "やげん軟骨",     "icon": "🍗", "limit": 2},
    {"name": "豚バラ肉",       "icon": "🥩", "limit": 3},
    {"name": "豚ロース肉",     "icon": "🥩", "limit": 3},
    {"name": "豚肩ロース肉",   "icon": "🥩", "limit": 3},
    {"name": "豚こま肉",       "icon": "🥩", "limit": 3},
    {"name": "豚しゃぶ肉",     "icon": "🥩", "limit": 3},
    {"name": "豚ヒレ肉",       "icon": "🥩", "limit": 3},
    {"name": "豚モモ肉",       "icon": "🥩", "limit": 3},
    {"name": "豚レバー",       "icon": "🥩", "limit": 2},
    {"name": "豚ひき肉",       "icon": "🥡", "limit": 1},
    {"name": "牛リブロース",   "icon": "🥩", "limit": 3},
    {"name": "牛肩ロース",     "icon": "🥩", "limit": 3},
    {"name": "牛サーロイン",   "icon": "🥩", "limit": 3},
    {"name": "牛モモ肉",       "icon": "🥩", "limit": 3},
    {"name": "牛ハラミ",       "icon": "🥩", "limit": 3},
    {"name": "牛タン",         "icon": "🥩", "limit": 3},
    {"name": "牛レバー",       "icon": "🥩", "limit": 2},
    {"name": "牛ひき肉",       "icon": "🥡", "limit": 1},
    {"name": "合挽き肉",       "icon": "🥡", "limit": 1},
    {"name": "ラム肉",         "icon": "🥩", "limit": 3},
    {"name": "馬肉",           "icon": "🥩", "limit": 2},
    {"name": "鴨肉",           "icon": "🍗", "limit": 2},
    {"name": "羊肉",           "icon": "🥩", "limit": 3},
  ],

  // ── 魚介類 ────────────────────────────────────────────
  "魚介類": [
    {"name": "鮭",             "icon": "🐟", "limit": 2},
    {"name": "マグロ",         "icon": "🍣", "limit": 1},
    {"name": "サバ",           "icon": "🐟", "limit": 2},
    {"name": "アジ",           "icon": "🐟", "limit": 2},
    {"name": "イワシ",         "icon": "🐟", "limit": 2},
    {"name": "サンマ",         "icon": "🐟", "limit": 2},
    {"name": "ブリ",           "icon": "🐟", "limit": 2},
    {"name": "ハマチ",         "icon": "🐟", "limit": 2},
    {"name": "タイ",           "icon": "🐟", "limit": 2},
    {"name": "ヒラメ",         "icon": "🐟", "limit": 2},
    {"name": "カレイ",         "icon": "🐟", "limit": 2},
    {"name": "タラ",           "icon": "🐟", "limit": 2},
    {"name": "サワラ",         "icon": "🐟", "limit": 2},
    {"name": "カツオ",         "icon": "🐟", "limit": 1},
    {"name": "シシャモ",       "icon": "🐟", "limit": 3},
    {"name": "アユ",           "icon": "🐟", "limit": 2},
    {"name": "ウナギ",         "icon": "🐟", "limit": 2},
    {"name": "アナゴ",         "icon": "🐟", "limit": 2},
    {"name": "えび",           "icon": "🦐", "limit": 2},
    {"name": "いか",           "icon": "🦑", "limit": 2},
    {"name": "たこ",           "icon": "🐙", "limit": 2},
    {"name": "かに",           "icon": "🦀", "limit": 2},
    {"name": "ホタテ",         "icon": "🐚", "limit": 2},
    {"name": "アサリ",         "icon": "🐚", "limit": 2},
    {"name": "シジミ",         "icon": "🐚", "limit": 2},
    {"name": "ハマグリ",       "icon": "🐚", "limit": 2},
    {"name": "カキ",           "icon": "🦪", "limit": 2},
    {"name": "ムール貝",       "icon": "🐚", "limit": 2},
    {"name": "サザエ",         "icon": "🐚", "limit": 3},
    {"name": "アワビ",         "icon": "🐚", "limit": 3},
    {"name": "いくら",         "icon": "🍣", "limit": 3},
    {"name": "たらこ",         "icon": "🍣", "limit": 3},
    {"name": "明太子",         "icon": "🍣", "limit": 3},
    {"name": "すじこ",         "icon": "🍣", "limit": 3},
    {"name": "シラス",         "icon": "🐟", "limit": 3},
  ],

  // ── 加工肉・ハム・ソーセージ ─────────────────────────
  "加工肉・ハム類": [
    {"name": "ロースハム",     "icon": "🥓", "limit": 7},
    {"name": "ボンレスハム",   "icon": "🥓", "limit": 7},
    {"name": "生ハム",         "icon": "🥓", "limit": 7},
    {"name": "ベーコン",       "icon": "🥓", "limit": 7},
    {"name": "厚切りベーコン", "icon": "🥓", "limit": 7},
    {"name": "ウインナー",     "icon": "🌭", "limit": 7},
    {"name": "フランクフルト", "icon": "🌭", "limit": 7},
    {"name": "ソーセージ",     "icon": "🌭", "limit": 7},
    {"name": "チョリソー",     "icon": "🌭", "limit": 7},
    {"name": "サラミ",         "icon": "🥓", "limit": 14},
    {"name": "ペパロニ",       "icon": "🥓", "limit": 14},
    {"name": "コンビーフ",     "icon": "🥓", "limit": 5},
    {"name": "スパム",         "icon": "🥓", "limit": 7},
    {"name": "魚肉ソーセージ", "icon": "🌭", "limit": 14},
    {"name": "ちくわ",         "icon": "🍢", "limit": 5},
    {"name": "かまぼこ",       "icon": "🍢", "limit": 5},
    {"name": "カニカマ",       "icon": "🍢", "limit": 5},
    {"name": "さつま揚げ",     "icon": "🍢", "limit": 5},
    {"name": "はんぺん",       "icon": "🍢", "limit": 5},
    {"name": "なると",         "icon": "🍢", "limit": 5},
    {"name": "つみれ",         "icon": "🍢", "limit": 3},
    {"name": "えびしんじょ",   "icon": "🍢", "limit": 3},
  ],

  // ── 乳製品・卵 ───────────────────────────────────────
  "乳製品・卵": [
    {"name": "牛乳",             "icon": "🥛", "limit": 7},
    {"name": "低脂肪牛乳",       "icon": "🥛", "limit": 7},
    {"name": "豆乳",             "icon": "🥛", "limit": 7},
    {"name": "アーモンドミルク", "icon": "🥛", "limit": 7},
    {"name": "生クリーム",       "icon": "🥛", "limit": 7},
    {"name": "ヨーグルト",       "icon": "🥚", "limit": 7},
    {"name": "ギリシャヨーグルト","icon": "🥚", "limit": 7},
    {"name": "バター",           "icon": "🧈", "limit": 30},
    {"name": "マーガリン",       "icon": "🧈", "limit": 30},
    {"name": "クリームチーズ",   "icon": "🧀", "limit": 14},
    {"name": "カマンベールチーズ","icon": "🧀", "limit": 14},
    {"name": "モッツァレラチーズ","icon": "🧀", "limit": 7},
    {"name": "チェダーチーズ",   "icon": "🧀", "limit": 14},
    {"name": "ゴーダチーズ",     "icon": "🧀", "limit": 14},
    {"name": "ブルーチーズ",     "icon": "🧀", "limit": 14},
    {"name": "スライスチーズ",   "icon": "🧀", "limit": 14},
    {"name": "粉チーズ",         "icon": "🧀", "limit": 30},
    {"name": "鶏卵",             "icon": "🥚", "limit": 14},
    {"name": "うずらの卵",       "icon": "🥚", "limit": 14},
    {"name": "温泉卵",           "icon": "🥚", "limit": 5},
    {"name": "ゆで卵",           "icon": "🥚", "limit": 3},
  ],

  // ── 豆腐・大豆製品 ───────────────────────────────────
  "豆腐・大豆製品": [
    {"name": "木綿豆腐",     "icon": "🫙", "limit": 5},
    {"name": "絹ごし豆腐",   "icon": "🫙", "limit": 5},
    {"name": "充填豆腐",     "icon": "🫙", "limit": 10},
    {"name": "厚揚げ",       "icon": "🫙", "limit": 5},
    {"name": "油揚げ",       "icon": "🫙", "limit": 5},
    {"name": "がんもどき",   "icon": "🫙", "limit": 5},
    {"name": "納豆",         "icon": "🫙", "limit": 7},
    {"name": "おから",       "icon": "🫙", "limit": 3},
    {"name": "豆乳ヨーグルト","icon": "🫙", "limit": 7},
    {"name": "高野豆腐",     "icon": "🫙", "limit": 180},
    {"name": "湯葉",         "icon": "🫙", "limit": 5},
    {"name": "大豆ミート",   "icon": "🫙", "limit": 5},
    {"name": "えだまめ",     "icon": "🫙", "limit": 3},
  ],

  // ── 野菜（葉物・キャベツ系） ─────────────────────────
  "葉物野菜": [
    {"name": "キャベツ",       "icon": "🥬", "limit": 14},
    {"name": "紫キャベツ",     "icon": "🥬", "limit": 14},
    {"name": "レタス",         "icon": "🥬", "limit": 5},
    {"name": "サニーレタス",   "icon": "🥬", "limit": 5},
    {"name": "ロメインレタス", "icon": "🥬", "limit": 5},
    {"name": "白菜",           "icon": "🥬", "limit": 14},
    {"name": "ほうれん草",     "icon": "🥬", "limit": 4},
    {"name": "小松菜",         "icon": "🥬", "limit": 4},
    {"name": "水菜",           "icon": "🥬", "limit": 5},
    {"name": "チンゲンサイ",   "icon": "🥬", "limit": 5},
    {"name": "春菊",           "icon": "🥬", "limit": 4},
    {"name": "ルッコラ",       "icon": "🥬", "limit": 3},
    {"name": "バジル",         "icon": "🌿", "limit": 5},
    {"name": "パセリ",         "icon": "🌿", "limit": 5},
    {"name": "大葉",           "icon": "🌿", "limit": 5},
    {"name": "三つ葉",         "icon": "🌿", "limit": 4},
    {"name": "パクチー",       "icon": "🌿", "limit": 4},
    {"name": "ミント",         "icon": "🌿", "limit": 5},
    {"name": "セロリ",         "icon": "🥬", "limit": 7},
    {"name": "菜の花",         "icon": "🥬", "limit": 4},
    {"name": "豆苗",           "icon": "🌱", "limit": 3},
    {"name": "もやし",         "icon": "🌱", "limit": 2},
    {"name": "ブロッコリースプラウト","icon": "🌱", "limit": 5},
  ],

  // ── 野菜（根菜・その他） ─────────────────────────────
  "根菜・その他野菜": [
    {"name": "にんじん",     "icon": "🥕", "limit": 14},
    {"name": "大根",         "icon": "🥕", "limit": 14},
    {"name": "ごぼう",       "icon": "🥕", "limit": 14},
    {"name": "れんこん",     "icon": "🥕", "limit": 14},
    {"name": "カブ",         "icon": "🥕", "limit": 7},
    {"name": "じゃがいも",   "icon": "🥔", "limit": 30},
    {"name": "さつまいも",   "icon": "🍠", "limit": 30},
    {"name": "里芋",         "icon": "🥔", "limit": 14},
    {"name": "長いも",       "icon": "🥕", "limit": 14},
    {"name": "山芋",         "icon": "🥕", "limit": 14},
    {"name": "たまねぎ",     "icon": "🧅", "limit": 30},
    {"name": "長ねぎ",       "icon": "🧅", "limit": 7},
    {"name": "小ねぎ",       "icon": "🌿", "limit": 5},
    {"name": "にんにく",     "icon": "🧄", "limit": 30},
    {"name": "しょうが",     "icon": "🧄", "limit": 14},
    {"name": "ブロッコリー", "icon": "🥦", "limit": 5},
    {"name": "カリフラワー", "icon": "🥦", "limit": 7},
    {"name": "アスパラガス", "icon": "🥦", "limit": 4},
    {"name": "トマト",       "icon": "🍅", "limit": 7},
    {"name": "ミニトマト",   "icon": "🍅", "limit": 7},
    {"name": "きゅうり",     "icon": "🥒", "limit": 7},
    {"name": "なす",         "icon": "🍆", "limit": 5},
    {"name": "ピーマン",     "icon": "🫑", "limit": 7},
    {"name": "パプリカ",     "icon": "🫑", "limit": 7},
    {"name": "ズッキーニ",   "icon": "🥒", "limit": 5},
    {"name": "ゴーヤ",       "icon": "🥒", "limit": 5},
    {"name": "オクラ",       "icon": "🥦", "limit": 3},
    {"name": "とうもろこし", "icon": "🌽", "limit": 3},
    {"name": "かぼちゃ",     "icon": "🎃", "limit": 30},
    {"name": "タケノコ",     "icon": "🥕", "limit": 3},
    {"name": "ニラ",         "icon": "🌿", "limit": 5},
  ],

  // ── きのこ類 ─────────────────────────────────────────
  "きのこ類": [
    {"name": "しいたけ",     "icon": "🍄", "limit": 5},
    {"name": "しめじ",       "icon": "🍄", "limit": 5},
    {"name": "えのき",       "icon": "🍄", "limit": 5},
    {"name": "まいたけ",     "icon": "🍄", "limit": 5},
    {"name": "エリンギ",     "icon": "🍄", "limit": 5},
    {"name": "なめこ",       "icon": "🍄", "limit": 5},
    {"name": "マッシュルーム","icon": "🍄", "limit": 5},
    {"name": "松茸",         "icon": "🍄", "limit": 3},
    {"name": "キクラゲ",     "icon": "🍄", "limit": 5},
  ],

  // ── 果物 ─────────────────────────────────────────────
  "果物": [
    {"name": "りんご",         "icon": "🍎", "limit": 14},
    {"name": "みかん",         "icon": "🍊", "limit": 7},
    {"name": "オレンジ",       "icon": "🍊", "limit": 7},
    {"name": "グレープフルーツ","icon": "🍊", "limit": 7},
    {"name": "レモン",         "icon": "🍋", "limit": 14},
    {"name": "バナナ",         "icon": "🍌", "limit": 5},
    {"name": "ぶどう",         "icon": "🍇", "limit": 5},
    {"name": "マスカット",     "icon": "🍇", "limit": 5},
    {"name": "いちご",         "icon": "🍓", "limit": 3},
    {"name": "ブルーベリー",   "icon": "🫐", "limit": 3},
    {"name": "ラズベリー",     "icon": "🍓", "limit": 2},
    {"name": "モモ",           "icon": "🍑", "limit": 4},
    {"name": "スイカ",         "icon": "🍉", "limit": 5},
    {"name": "メロン",         "icon": "🍈", "limit": 5},
    {"name": "梨",             "icon": "🍐", "limit": 7},
    {"name": "柿",             "icon": "🍊", "limit": 7},
    {"name": "キウイ",         "icon": "🥝", "limit": 7},
    {"name": "パイナップル",   "icon": "🍍", "limit": 5},
    {"name": "マンゴー",       "icon": "🥭", "limit": 5},
    {"name": "アボカド",       "icon": "🥑", "limit": 3},
    {"name": "さくらんぼ",     "icon": "🍒", "limit": 3},
    {"name": "プラム",         "icon": "🍑", "limit": 4},
    {"name": "梅",             "icon": "🍊", "limit": 3},
    {"name": "ゆず",           "icon": "🍋", "limit": 14},
    {"name": "シークワーサー", "icon": "🍋", "limit": 14},
  ],

  // ── 主食・麺類・パン ─────────────────────────────────
  "主食・麺・パン": [
    {"name": "白米",           "icon": "🍚", "limit": 14},
    {"name": "玄米",           "icon": "🍚", "limit": 14},
    {"name": "冷凍ご飯",       "icon": "🍚", "limit": 30},
    {"name": "うどん（生）",   "icon": "🍜", "limit": 5},
    {"name": "そば（生）",     "icon": "🍜", "limit": 5},
    {"name": "ラーメン（生）", "icon": "🍜", "limit": 5},
    {"name": "中華麺",         "icon": "🍜", "limit": 5},
    {"name": "パスタ",         "icon": "🍝", "limit": 730},
    {"name": "そうめん",       "icon": "🍜", "limit": 730},
    {"name": "食パン",         "icon": "🍞", "limit": 5},
    {"name": "ロールパン",     "icon": "🍞", "limit": 3},
    {"name": "フランスパン",   "icon": "🥖", "limit": 3},
    {"name": "クロワッサン",   "icon": "🥐", "limit": 3},
    {"name": "ベーグル",       "icon": "🥯", "limit": 3},
    {"name": "ピタパン",       "icon": "🫓", "limit": 3},
    {"name": "米粉パン",       "icon": "🍞", "limit": 3},
    {"name": "ナン",           "icon": "🫓", "limit": 3},
    {"name": "餃子の皮",       "icon": "🥟", "limit": 5},
    {"name": "春巻きの皮",     "icon": "🥟", "limit": 5},
    {"name": "ワンタンの皮",   "icon": "🥟", "limit": 5},
  ],

  // ── 冷凍食品 ─────────────────────────────────────────
  "冷凍食品": [
    {"name": "冷凍餃子",         "icon": "🥟", "limit": 60},
    {"name": "冷凍唐揚げ",       "icon": "🍗", "limit": 60},
    {"name": "冷凍エビフライ",   "icon": "🍤", "limit": 60},
    {"name": "冷凍コロッケ",     "icon": "🍤", "limit": 60},
    {"name": "冷凍ハンバーグ",   "icon": "🍔", "limit": 60},
    {"name": "冷凍たこ焼き",     "icon": "🐙", "limit": 60},
    {"name": "冷凍お好み焼き",   "icon": "🥞", "limit": 60},
    {"name": "冷凍ピザ",         "icon": "🍕", "limit": 60},
    {"name": "冷凍炒飯",         "icon": "🍚", "limit": 60},
    {"name": "冷凍うどん",       "icon": "🍜", "limit": 60},
    {"name": "冷凍ラーメン",     "icon": "🍜", "limit": 60},
    {"name": "冷凍パスタ",       "icon": "🍝", "limit": 60},
    {"name": "冷凍シューマイ",   "icon": "🥟", "limit": 60},
    {"name": "冷凍グラタン",     "icon": "🍲", "limit": 60},
    {"name": "冷凍春巻き",       "icon": "🥟", "limit": 60},
    {"name": "冷凍えび",         "icon": "🦐", "limit": 60},
    {"name": "冷凍いか",         "icon": "🦑", "limit": 60},
    {"name": "冷凍ホタテ",       "icon": "🐚", "limit": 60},
    {"name": "冷凍ブロッコリー", "icon": "🥦", "limit": 60},
    {"name": "冷凍ほうれん草",   "icon": "🥬", "limit": 60},
    {"name": "冷凍枝豆",         "icon": "🫛", "limit": 60},
    {"name": "冷凍コーン",       "icon": "🌽", "limit": 60},
    {"name": "冷凍アイスクリーム","icon": "🍦", "limit": 60},
    {"name": "冷凍フルーツ",     "icon": "🍓", "limit": 60},
  ],

  // ── レトルト・インスタント ───────────────────────────
  "レトルト・インスタント": [
    {"name": "カレールー（レトルト）","icon": "🍛", "limit": 180},
    {"name": "ハヤシライス（レトルト）","icon": "🍛", "limit": 180},
    {"name": "麻婆豆腐の素",     "icon": "🍲", "limit": 180},
    {"name": "八宝菜の素",       "icon": "🍲", "limit": 180},
    {"name": "親子丼の素",       "icon": "🍲", "limit": 180},
    {"name": "牛丼の素",         "icon": "🍲", "limit": 180},
    {"name": "中華丼の素",       "icon": "🍲", "limit": 180},
    {"name": "パスタソース",     "icon": "🍝", "limit": 180},
    {"name": "インスタント味噌汁","icon": "🍵", "limit": 180},
    {"name": "インスタントラーメン","icon": "🍜", "limit": 180},
    {"name": "カップ麺",         "icon": "🍜", "limit": 180},
    {"name": "カップ焼きそば",   "icon": "🍜", "limit": 180},
    {"name": "おでんセット",     "icon": "🍢", "limit": 30},
    {"name": "鍋つゆ",           "icon": "🍲", "limit": 180},
    {"name": "アルファ米",       "icon": "🍚", "limit": 1825},
  ],

  // ── 缶詰・瓶詰め ─────────────────────────────────────
  "缶詰・瓶詰め": [
    {"name": "ツナ缶",           "icon": "🥫", "limit": 1095},
    {"name": "サバ缶（水煮）",   "icon": "🥫", "limit": 1095},
    {"name": "サバ缶（味噌煮）", "icon": "🥫", "limit": 1095},
    {"name": "イワシ缶",         "icon": "🥫", "limit": 1095},
    {"name": "サーモン缶",       "icon": "🥫", "limit": 1095},
    {"name": "貝柱缶",           "icon": "🥫", "limit": 1095},
    {"name": "かに缶",           "icon": "🥫", "limit": 1095},
    {"name": "焼き鳥缶",         "icon": "🥫", "limit": 1095},
    {"name": "コーン缶",         "icon": "🥫", "limit": 1095},
    {"name": "トマト缶",         "icon": "🥫", "limit": 1095},
    {"name": "豆缶（ミックス）", "icon": "🥫", "limit": 1095},
    {"name": "フルーツ缶",       "icon": "🥫", "limit": 1095},
    {"name": "オリーブ",         "icon": "🫙", "limit": 180},
    {"name": "いちごジャム",     "icon": "🫙", "limit": 180},
    {"name": "ブルーベリージャム","icon": "🫙", "limit": 180},
    {"name": "マーマレード",     "icon": "🫙", "limit": 180},
    {"name": "りんごジャム",     "icon": "🫙", "limit": 180},
    {"name": "ピーナッツバター", "icon": "🫙", "limit": 180},
    {"name": "はちみつ",         "icon": "🫙", "limit": 730},
    {"name": "メープルシロップ", "icon": "🫙", "limit": 365},
    {"name": "ジャム（その他）", "icon": "🫙", "limit": 180},
  ],

  // ── 漬物・発酵食品 ───────────────────────────────────
  "漬物・発酵食品": [
    {"name": "キムチ",         "icon": "🥬", "limit": 14},
    {"name": "たくあん",       "icon": "🥒", "limit": 14},
    {"name": "ぬか漬け",       "icon": "🥒", "limit": 5},
    {"name": "浅漬け",         "icon": "🥒", "limit": 3},
    {"name": "しば漬け",       "icon": "🥒", "limit": 14},
    {"name": "梅干し",         "icon": "🍊", "limit": 365},
    {"name": "らっきょう",     "icon": "🧅", "limit": 90},
    {"name": "福神漬け",       "icon": "🥒", "limit": 30},
    {"name": "ザワークラウト", "icon": "🥬", "limit": 14},
    {"name": "海苔の佃煮",     "icon": "🌊", "limit": 14},
    {"name": "昆布の佃煮",     "icon": "🌊", "limit": 14},
    {"name": "ちりめんじゃこ", "icon": "🐟", "limit": 7},
  ],

  // ── 調味料 ───────────────────────────────────────────
  "調味料": [
    {"name": "醤油",           "icon": "🫙", "limit": 180},
    {"name": "味噌",           "icon": "🫙", "limit": 90},
    {"name": "みりん",         "icon": "🫙", "limit": 180},
    {"name": "料理酒",         "icon": "🫙", "limit": 180},
    {"name": "酢",             "icon": "🫙", "limit": 180},
    {"name": "ポン酢",         "icon": "🫙", "limit": 90},
    {"name": "マヨネーズ",     "icon": "🫙", "limit": 90},
    {"name": "ケチャップ",     "icon": "🍅", "limit": 90},
    {"name": "ウスターソース", "icon": "🫙", "limit": 90},
    {"name": "中濃ソース",     "icon": "🫙", "limit": 90},
    {"name": "オイスターソース","icon": "🫙", "limit": 90},
    {"name": "豆板醤",         "icon": "🫙", "limit": 90},
    {"name": "コチュジャン",   "icon": "🫙", "limit": 90},
    {"name": "甜麺醤",         "icon": "🫙", "limit": 90},
    {"name": "ナンプラー",     "icon": "🫙", "limit": 90},
    {"name": "オリーブオイル", "icon": "🫙", "limit": 180},
    {"name": "ごま油",         "icon": "🫙", "limit": 180},
    {"name": "サラダ油",       "icon": "🫙", "limit": 180},
    {"name": "ラー油",         "icon": "🫙", "limit": 180},
    {"name": "塩",             "icon": "🫙", "limit": 1825},
    {"name": "砂糖",           "icon": "🫙", "limit": 1825},
    {"name": "黒糖",           "icon": "🫙", "limit": 365},
    {"name": "胡椒",           "icon": "🫙", "limit": 365},
    {"name": "わさび",         "icon": "🫙", "limit": 30},
    {"name": "からし",         "icon": "🫙", "limit": 30},
    {"name": "タバスコ",       "icon": "🫙", "limit": 180},
    {"name": "カレー粉",       "icon": "🫙", "limit": 365},
    {"name": "鶏がらスープの素","icon": "🫙", "limit": 365},
    {"name": "コンソメ",       "icon": "🫙", "limit": 365},
    {"name": "だしの素",       "icon": "🫙", "limit": 365},
    {"name": "めんつゆ",       "icon": "🫙", "limit": 90},
    {"name": "ドレッシング",   "icon": "🫙", "limit": 90},
    {"name": "ごまだれ",       "icon": "🫙", "limit": 60},
    {"name": "焼肉のたれ",     "icon": "🫙", "limit": 90},
    {"name": "テリヤキソース", "icon": "🫙", "limit": 90},
    {"name": "バーベキューソース","icon": "🫙", "limit": 90},
  ],

  // ── 飲み物 ───────────────────────────────────────────
  "飲み物": [
    {"name": "ミネラルウォーター","icon": "💧", "limit": 180},
    {"name": "緑茶",           "icon": "🍵", "limit": 7},
    {"name": "麦茶",           "icon": "🍵", "limit": 7},
    {"name": "烏龍茶",         "icon": "🍵", "limit": 7},
    {"name": "紅茶",           "icon": "🫖", "limit": 7},
    {"name": "コーヒー",       "icon": "☕", "limit": 7},
    {"name": "オレンジジュース","icon": "🧃", "limit": 7},
    {"name": "りんごジュース", "icon": "🧃", "limit": 7},
    {"name": "野菜ジュース",   "icon": "🧃", "limit": 7},
    {"name": "牛乳コーヒー",   "icon": "🥛", "limit": 7},
    {"name": "コーラ",         "icon": "🥤", "limit": 14},
    {"name": "サイダー",       "icon": "🥤", "limit": 14},
    {"name": "スポーツドリンク","icon": "🥤", "limit": 14},
    {"name": "エナジードリンク","icon": "🥤", "limit": 14},
    {"name": "ビール",         "icon": "🍺", "limit": 90},
    {"name": "発泡酒",         "icon": "🍺", "limit": 90},
    {"name": "チューハイ",     "icon": "🍺", "limit": 90},
    {"name": "日本酒",         "icon": "🍶", "limit": 90},
    {"name": "ワイン（赤）",   "icon": "🍷", "limit": 90},
    {"name": "ワイン（白）",   "icon": "🍷", "limit": 90},
    {"name": "ハイボール",     "icon": "🥃", "limit": 90},
  ],

  // ── お菓子・デザート ─────────────────────────────────
  "お菓子・デザート": [
    {"name": "プリン",         "icon": "🍮", "limit": 7},
    {"name": "ゼリー",         "icon": "🍮", "limit": 7},
    {"name": "ヨーグルトゼリー","icon": "🍮", "limit": 7},
    {"name": "シュークリーム", "icon": "🍰", "limit": 2},
    {"name": "エクレア",       "icon": "🍰", "limit": 2},
    {"name": "ケーキ",         "icon": "🎂", "limit": 3},
    {"name": "チーズケーキ",   "icon": "🍰", "limit": 3},
    {"name": "モンブラン",     "icon": "🍰", "limit": 2},
    {"name": "大福",           "icon": "🍡", "limit": 3},
    {"name": "みたらし団子",   "icon": "🍡", "limit": 2},
    {"name": "どら焼き",       "icon": "🍡", "limit": 3},
    {"name": "わらび餅",       "icon": "🍡", "limit": 3},
    {"name": "羊羹",           "icon": "🍡", "limit": 14},
    {"name": "チョコレート",   "icon": "🍫", "limit": 90},
    {"name": "クッキー",       "icon": "🍪", "limit": 30},
    {"name": "アイスクリーム", "icon": "🍦", "limit": 30},
    {"name": "ソフトクリーム", "icon": "🍦", "limit": 7},
    {"name": "かき氷",         "icon": "🍧", "limit": 30},
    {"name": "杏仁豆腐",       "icon": "🍮", "limit": 5},
    {"name": "ムース",         "icon": "🍮", "limit": 3},
    {"name": "マカロン",       "icon": "🍪", "limit": 5},
    {"name": "タルト",         "icon": "🍰", "limit": 3},
  ],
};